---
title: "Milestone 2"
author: "Amy Tan"
date: "9/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Pros and Cons of Projects from Different Years:

Project 1: U.S. Federal Crime Data by Sabrina Chok

This dataset includes a very extensive dataset of federal crime data nationwide in the U.S. from 2010 to 2017. I really liked how the first interactive function called "State Comparisons" worked because you can type in any state, instead of choosing from a drop-down menu, and it would give you the relevant data on a line graph compared to another state and the national trend. However, one drawback of this is that if you type in a state in lowercase, then it would not output the data for that state. Another thing that could be improved upon is that for the line graphs, it's hard to tell what the individual points were since the lines are so thin. I would add dots for each data point on the line. I also liked how I was able to see the overall trends in terms of states with the highest rates of different crimes via the Annual Comparisons tab and the Top 10 Highest Violent Crime States tab. The added detail of being able to select how many states were included in the chart was really helpful for exploring the data. I also love the animation of the Top 10 Highest Violent Crime States because it gives a visual representation for how trends have changed over time. 

Project 2: Analyzing Crime in Chicago, 2008-2018 by Taehwan Kim

This dataset shows crime rates in Chicago from 2008-2018. I like how it gives a bit of context on the home tab as to why this is important and interesting question to investigate. On the Yearly Trends tab, I liked how I was able to adjust the time horizon to see both short-term and long-term trends. Again, my critique of this is that it is hard to tell individual data points without the dots on the lines. For the By Time tab, I would improve it by making Arrested or Not Arrested different colors in the bar graph, so viewers can compare what the arrest rates are like compared to the crime rates. I found it really interesting how he broke down crime rates by time, though, because that can lead to new questions about why there's significantly lower crime rates at certain times of the day, week, or month. For the month option, it was pretty strange to see a 12.5 on the x-axis because obviously, there is no 12.5 month. I would relabel them the actual names of the months. It was cool that he plotted the crime rates geographically and colored each region differently to show those who aren't as familar with Chicago's landscape the different divisions of crime rates by area.
